trigger: 
  - master

steps: 
  - task: AzureResourceGroupDeployment@2
    inputs: 
      azureSubscription: 'Azure subscription'
      resourceGroupName: 'AzureskolenTest'
      location: westeurope # norwayeast
      csmFile:  $(Build.Repository.LocalPath)/AzureWorkshopInfrastruktur/AzureWorkshopInfrastruktur/azuredeploy.json
      csmParametersFile:  $(Build.Repository.LocalPath)/AzureWorkshopInfrastruktur/AzureWorkshopInfrastruktur/azuredeploy.parameters.json